#!/usr/sbin/nft -f

# Flush existing rules
flush ruleset

# Define the main table
table inet filter {
    
    # Chain for input traffic
    chain input {
        type filter hook input priority filter; policy accept;

	iif enp0s3 accept
	iif lo accept

        # Per-IP rate limiting using meters
        # Each IP is limited to 10 packets/second
        # Packets exceeding the rate are dropped
        meter ratelimit { ip saddr limit rate over 10/second burst 5 packets} drop
	
	accept
       
    }
    
    # Chain for forward traffic
    chain forward {
        type filter hook forward priority filter; policy accept;
    }
    
    # Chain for output traffic
    chain output {
        type filter hook output priority filter; policy accept;
    }
}
